name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: clones the github repo
        uses: actions/checkout@v2
        with:
          repository: "tymscar/github-actions-test"

      - name: prints all files in gh repo
        run: ls -la
