name: Matrix
on: workflow_dispatch

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [6, 8, 10, 12, 14, 16]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node node-version
        run: node -v
