name: Testing ripgrep in gha 

on: push
jobs:
  testing-ripgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest ripgrep in gha
        run: |
          wget ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
          sudo mv ripgrep-14.1.1-x86_64-unknown-linux-musl/rg /usr/local/bin
          rg --version
      - name: Run ripgrep on stdinput
        run: echo "Hello, world!" | rg "Hello"
      - name: create a file with a message
        run: echo "Hello, world!" > hello.txt
      - name: Run ripgrep on a file
        run: rg "Hello" hello.txt  
      - name: Run ripgrep without specifying a file (will fail, so debug)
        run: rg --debug "Hello"
