name: Testing ripgrep in gha 

on: push
jobs:
  testing-ripgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Install ripgrep in gha
        run: sudo apt-get install ripgrep
      - name: Run ripgrep on stdinput
        run: echo "Hello, world!" | rg "Hello"
      - name: create a file with a message
        run: echo "Hello, world!" > hello.txt
      - name: Run ripgrep on a file
        run: rg "Hello" hello.txt  
      - name: Run ripgrep without specifying a file
        run: rg "Hello"
