name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo os details
        run: uname -a
      - name: print processor info from python
        run: |
          import platform
          platform.processor()
        shell: python
